### ISSUE TITLE
Having trouble loading in

### ISSUE THREAD

**Issue by MarkoCracker** [JamieFristrom/dungeonlife#6]
Hello, There Is an Issue when I load the game into ROBLOX Studio.

The game wont fully load.

Does anyone have a suggestion to fix it?

**Comment by MarkoCracker** [comment]
Here's an Image

![Capture](https://user-images.githubusercontent.com/61752819/83980447-4463fe80-a916-11ea-9eed-78f28a44bcf3.PNG)

**Comment by jafristr** [comment]
Could be a bunch of things. Talk to me in the Dungeon Life discord if you want faster turnarounds. Did the typescript seem to compile ok, did the lua files make it through rojo, etc.

**Comment by JamieFristrom** [comment]
Assuming it was one of the above problems and closing.
